algoritmo "semnome"
// Função : Calcular média de 2 notas
// Autor :  Enzo Siqueira
// Data : 26/04/2022
// Seção de Declarações 
var
p1: real
p2: real
media: real

inicio
// DADOS DE ENTRADA
escreval("Escreva P1: ")
leia(p1)
escreval("Escreva P2: ")
leia(p2)
//FIM DOS DADOS DE ENTRADA

//PROCESSAMENTO
media <- (p1+p2)/2
//FIM_PROCESSAMENTO

//DADOS DE SAÍDA
escreval("A média do aluno é: ",media, " !")
//FIM DOS DADOS DE SAÍDA

fimalgoritmo
