Algoritmo "ex02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Enzo Siqueira
// Data atual  : 29/09/2022
Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para cont de 100 ate 200 faca
   se cont mod 2 <> 0 entao
      escreval(cont)
   fimse
fimpara


Fimalgoritmo